{
 "title": "Netbox Docker Agents",
 "description": "Dashboard for netbox-docker-agent metrics",
 "tags": [
  "docker",
  "netbox"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Runtime per Container",
   "type": "table",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  netbox_docker_agent_container_running\r\n  or netbox_docker_agent_container_exited\r\n  or netbox_docker_agent_container_stopped,\r\n  \"clean_name\",\r\n  \"$1\",\r\n  \"name\",\r\n  \"^(.+?)(?:-[0-9]{13})?$\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Containers Running",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\ncount(\r\n  max by (name) (\r\n    netbox_docker_agent_container_running\r\n  ) == 1\r\n)\r\n/\r\ncount(\r\n  max by (name) (\r\n    netbox_docker_agent_container_running\r\n    or\r\n    netbox_docker_agent_container_exited\r\n    or\r\n    netbox_docker_agent_container_stopped\r\n  )\r\n)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Netbox Errors",
   "type": "stat",
   "gridPos": { "x": 20, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netbox_docker_agent_netbox_error_response",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Docker Daemon",
   "type": "stat",
   "gridPos": { "x": 20, "y": 4, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netbox_docker_agent_docker_daemon",
     "legendFormat": "Daemon"
    }
   ]
  },
  {
   "title": "Container Running History",
   "type": "status-history",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 40 },
   "targets": [
    {
     "expr": "max by (normalized_name) (\r\n  label_replace(\r\n    (\r\n      netbox_docker_agent_container_running\r\n      or\r\n      (netbox_docker_agent_container_exited * 0)\r\n      or\r\n      (netbox_docker_agent_container_stopped * 0)\r\n    ),\r\n    \"normalized_name\",\r\n    \"$1\",\r\n    \"name\",\r\n    \"^(.*?)(-[0-9]+)?$\"\r\n  )\r\n)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}