{
 "title": "Grafana",
 "description": "Grafana Internal Metrics Dashboards",
 "tags": [
  "grafana",
  "internal metrics"
 ],
 "time": {
  "from": "now-6h",
  "to": "now",
  "expr": {
   "expr": null
  }
 },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "General Counters",
   "type": "row",
   "gridPos": {
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 0,
    "expr": {
     "expr": null
    }
   }
  },
  {
   "title": "Grafana Version",
   "type": "table",
   "gridPos": {
    "h": 7,
    "w": 6,
    "x": 0,
    "y": 1,
    "expr": {
     "expr": null
    }
   },
   "targets": [
    {
     "expr": "grafana_build_info{instance=~\".*grafana:3000\"}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "description": "Count of Active users",
   "gridPos": {
    "h": 6,
    "w": 5,
    "x": 6,
    "y": 1,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_active_admins{instance=~\".*grafana:3000\"}",
     "legendFormat": "Active Admins"
    },
    {
     "expr": "grafana_stat_totals_active_editors{instance=~\".*grafana:3000\"}",
     "legendFormat": "Active Editors"
    },
    {
     "expr": "grafana_stat_totals_active_viewers{instance=~\".*grafana:3000\"}",
     "legendFormat": "Active Viewers"
    }
   ]
  },
  {
   "title": "Dashboards",
   "type": "stat",
   "description": "total amount of dashboards",
   "gridPos": {
    "h": 4,
    "w": 5,
    "x": 11,
    "y": 1,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_dashboard{instance=~\".*grafana:3000\"}"
    }
   ]
  },
  {
   "title": "Grafana Up",
   "type": "timeseries",
   "description": "Show if instance us Up or Down. Default Prometheus Metric.\n\nIf target is not reachable this will have 0 value",
   "gridPos": {
    "h": 7,
    "w": 8,
    "x": 16,
    "y": 1,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=~\".*grafana:3000\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "description": "total amount of alerts",
   "gridPos": {
    "h": 3,
    "w": 5,
    "x": 11,
    "y": 5,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grafana_alerting_alerts{instance=~\".*grafana:3000\"})"
    }
   ]
  },
  {
   "title": "Total Service Accounts",
   "type": "stat",
   "description": "Total Service Accounts",
   "gridPos": {
    "h": 5,
    "w": 5,
    "x": 6,
    "y": 7,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_service_accounts{instance=~\".*grafana:3000\"}",
     "legendFormat": "Service Accounts"
    },
    {
     "expr": "grafana_stat_total_service_account_tokens{instance=~\".*grafana:3000\"}",
     "legendFormat": "Tokens"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "description": "total amount of users",
   "gridPos": {
    "h": 4,
    "w": 3,
    "x": 0,
    "y": 8,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_users{instance=~\".*grafana:3000\"}"
    }
   ]
  },
  {
   "title": "Admins",
   "type": "stat",
   "description": "Total amount of Admins",
   "gridPos": {
    "h": 4,
    "w": 3,
    "x": 3,
    "y": 8,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_admins{instance=~\".*grafana:3000\"}"
    }
   ]
  },
  {
   "title": "Organisations",
   "type": "stat",
   "description": "total amount of orgs",
   "gridPos": {
    "h": 4,
    "w": 3,
    "x": 11,
    "y": 8,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_orgs{instance=~\".*grafana:3000\"}"
    }
   ]
  },
  {
   "title": "Folders",
   "type": "stat",
   "description": "total amount of folders",
   "gridPos": {
    "h": 4,
    "w": 2,
    "x": 14,
    "y": 8,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_folder{instance=~\".*grafana:3000\"}"
    }
   ]
  },
  {
   "title": "Access Evaluations Total",
   "type": "stat",
   "description": "Access Evaluations Total in Timeframe",
   "gridPos": {
    "h": 4,
    "w": 8,
    "x": 16,
    "y": 8,
    "expr": {
     "expr": null
    }
   },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(grafana_access_evaluation_count{instance=~\".*grafana:3000\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Alerting",
   "type": "row",
   "gridPos": {
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 12,
    "expr": {
     "expr": null
    }
   }
  },
  {
   "title": "Alerts State",
   "type": "stat",
   "description": "State of the Alerts in orgs",
   "gridPos": {
    "h": 9,
    "w": 12,
    "x": 0,
    "y": 13,
    "expr": {
     "expr": null
    }
   },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_alerting_alerts{instance=~\".*grafana:3000\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Alerts State",
   "type": "timeseries",
   "description": "State of the Alerts in orgs",
   "gridPos": {
    "h": 9,
    "w": 12,
    "x": 12,
    "y": 13,
    "expr": {
     "expr": null
    }
   },
   "targets": [
    {
     "expr": "increase(grafana_alerting_alerts{instance=~\".*grafana:3000\"}[$__interval]) > 0",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": {
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 22,
    "expr": {
     "expr": null
    }
   },
   "targets": [
    {
     "expr": {
      "expr": null
     }
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": {
    "h": 7,
    "w": 8,
    "x": 0,
    "y": 23,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=~\".*grafana:3000\"}[$__rate_interval]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": {
    "h": 7,
    "w": 8,
    "x": 8,
    "y": 23,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=~\".*grafana:3000\"}[$__rate_interval]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{instance=~\".*grafana:3000\"}[$__rate_interval]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": {
    "h": 7,
    "w": 8,
    "x": 16,
    "y": 23,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\".*grafana:3000\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": {
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 30,
    "expr": {
     "expr": null
    }
   }
  },
  {
   "title": "DB Open Connections",
   "type": "bargauge",
   "gridPos": {
    "h": 8,
    "w": 12,
    "x": 0,
    "y": 31,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_database_conn_open{instance=~\".*grafana:3000\"} /\ngrafana_database_conn_max_open{instance=~\".*grafana:3000\"} *100",
     "legendFormat": "open conn"
    }
   ]
  },
  {
   "title": "DB Open Connections",
   "type": "timeseries",
   "gridPos": {
    "h": 8,
    "w": 12,
    "x": 12,
    "y": 31,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "grafana_database_conn_open{instance=~\".*grafana:3000\"}",
     "legendFormat": "open conn"
    }
   ]
  },
  {
   "title": "Connection Wait Count",
   "type": "timeseries",
   "gridPos": {
    "h": 8,
    "w": 12,
    "x": 0,
    "y": 39,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(grafana_database_conn_wait_count_total{instance=~\".*grafana:3000\"}[$__interval])",
     "legendFormat": "conn wait count"
    }
   ]
  },
  {
   "title": "Connection Wait Seconds",
   "type": "timeseries",
   "gridPos": {
    "h": 8,
    "w": 12,
    "x": 12,
    "y": 39,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(grafana_database_conn_wait_duration_seconds{instance=~\".*grafana:3000\"}[$__interval])",
     "legendFormat": "conn wait count"
    }
   ]
  },
  {
   "title": "Responce Codes and Logins",
   "type": "row",
   "gridPos": {
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 47,
    "expr": {
     "expr": null
    }
   },
   "targets": [
    {
     "expr": {
      "expr": null
     }
    }
   ]
  },
  {
   "title": "Total Response Statuses",
   "type": "bargauge",
   "description": "http response status",
   "gridPos": {
    "h": 11,
    "w": 24,
    "x": 0,
    "y": 48,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(grafana_api_response_status_total{instance=~\".*grafana:3000\"}[$__interval])",
     "legendFormat": "API {{ code }}"
    },
    {
     "expr": "increase(grafana_page_response_status_total{instance=~\".*grafana:3000\"}[$__interval])",
     "legendFormat": "Page {{ code }}"
    },
    {
     "expr": "increase(grafana_proxy_response_status_total{instance=~\".*grafana:3000\"}[$__interval])",
     "legendFormat": "Proxy {{ code }}"
    }
   ]
  },
  {
   "title": "Total Response Statuses",
   "type": "timeseries",
   "description": "http response status",
   "gridPos": {
    "h": 11,
    "w": 24,
    "x": 0,
    "y": 59,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(grafana_api_response_status_total{instance=~\".*grafana:3000\"}[$__interval])",
     "legendFormat": "API {{ code }}"
    },
    {
     "expr": "increase(grafana_page_response_status_total{instance=~\".*grafana:3000\"}[$__interval])",
     "legendFormat": "Page {{ code }}"
    },
    {
     "expr": "increase(grafana_proxy_response_status_total{instance=~\".*grafana:3000\"}[$__interval])",
     "legendFormat": "Proxy {{ code }}"
    }
   ]
  },
  {
   "title": "Login Counts",
   "type": "timeseries",
   "description": "api login counters",
   "gridPos": {
    "h": 8,
    "w": 24,
    "x": 0,
    "y": 70,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafana_api_login_post_total{instance=~\".*grafana:3000\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "grafana_api_login_oauth_total{instance=~\".*grafana:3000\"}",
     "legendFormat": "OAuth"
    }
   ]
  },
  {
   "title": "Dashboard Get Stats",
   "type": "row",
   "gridPos": {
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 78,
    "expr": {
     "expr": null
    }
   },
   "targets": [
    {
     "expr": {
      "expr": null
     }
    }
   ]
  },
  {
   "title": "Dashboard Get Duration Avg",
   "type": "timeseries",
   "description": "average dashboard get duration",
   "gridPos": {
    "h": 7,
    "w": 12,
    "x": 0,
    "y": 79,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_get_milliseconds_sum{instance=~\".*grafana:3000\"}[$__rate_interval]) / rate(grafana_api_dashboard_get_milliseconds_count{instance=~\".*grafana:3000\"}[$__rate_interval])",
     "legendFormat": "avg get duration"
    }
   ]
  },
  {
   "title": "Dashboard Get Duration Quantiles",
   "type": "histogram",
   "description": "\nThe provided Prometheus query is designed to calculate the 50th | 90 | 99 percentile (median) of the latency distribution for Grafana alerting notifications over a specified time range. Here's a breakdown of the query and its description:",
   "gridPos": {
    "h": 7,
    "w": 12,
    "x": 12,
    "y": 79,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "grafana_api_dashboard_get_milliseconds{instance=~\".*grafana:3000\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Dashboard Save Stats",
   "type": "row",
   "gridPos": {
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 86,
    "expr": {
     "expr": null
    }
   },
   "targets": [
    {
     "expr": {
      "expr": null
     }
    }
   ]
  },
  {
   "title": "Dashboard Save Duration Avg",
   "type": "timeseries",
   "description": "average dashboard save duration over  $__rate_interval minutes",
   "gridPos": {
    "h": 7,
    "w": 12,
    "x": 0,
    "y": 87,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_save_milliseconds_sum{instance=~\".*grafana:3000\"}[$__rate_interval]) / rate(grafana_api_dashboard_save_milliseconds_count{instance=~\".*grafana:3000\"}[$__rate_interval])",
     "legendFormat": "avg save duration"
    }
   ]
  },
  {
   "title": "Dashboard Save Duration Quantiles",
   "type": "histogram",
   "description": "Dashboard Save Duration Quantiles",
   "gridPos": {
    "h": 7,
    "w": 12,
    "x": 12,
    "y": 87,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "grafana_api_dashboard_save_milliseconds{instance=~\".*grafana:3000\",}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Dashboard Search Stats",
   "type": "row",
   "gridPos": {
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 94,
    "expr": {
     "expr": null
    }
   },
   "targets": [
    {
     "expr": {
      "expr": null
     }
    }
   ]
  },
  {
   "title": "Dashboard Search Duration Avg",
   "type": "timeseries",
   "description": "average dashboard search duration over $__rate_interval minutes",
   "gridPos": {
    "h": 7,
    "w": 12,
    "x": 0,
    "y": 95,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_search_milliseconds_sum{instance=~\".*grafana:3000\"}[$__rate_interval]) / \nrate(grafana_api_dashboard_search_milliseconds_count{instance=~\".*grafana:3000\"}[$__rate_interval])",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Dashboard Search Duration Quantiles",
   "type": "histogram",
   "description": "Dashboard Search Duration Quantiles",
   "gridPos": {
    "h": 7,
    "w": 12,
    "x": 12,
    "y": 95,
    "expr": {
     "expr": null
    }
   },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "grafana_api_dashboard_search_milliseconds{instance=~\".*grafana:3000\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  }
 ]
}